name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: simpple-python-app:latest
          outputs: type=docker,dest=/tmp/simpple-python-app.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simpple-python-app
          path: /tmp/simpple-python-app.tar


  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simpple-python-app
          path: /tmp

      - name: Run Trivy vulnerability scan
        run: |
          docker load --input /tmp/simpple-python-app.tar
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL simple-python-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simpple-python-app
          path: /tmp

      - name: Deploy to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker load --input /tmp/simpple-python-app.tar
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker tag simple-python-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/simple-python-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-python-app:latest
