name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      started_time: ${{ steps.job-start.outputs.STARTED_TIME }}
    
    steps:

      - name: Job start
        id: job-start
        run: |
          echo "STARTED_TIME=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: simple-python-app:${{ github.sha }}
          outputs: type=docker,dest=/tmp/simple-python-app.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-python-app
          path: /tmp/simple-python-app.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simple-python-app
          path: /tmp

      - name: Run Trivy vulnerability scan
        run: |
          docker load --input /tmp/simple-python-app.tar
          docker image ls -a  
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity HIGH,CRITICAL simple-python-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ "build", "test"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simple-python-app
          path: /tmp

      - name: Deploy to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker load --input /tmp/simple-python-app.tar
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker tag simple-python-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/simple-python-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-python-app:${{ github.sha }}

      - name: Send info to Datadog
        env:
          STARTED_TIME: ${{ needs.job-start.outputs.STARTED_TIME }}
        run: |
          curl -X POST "https://api.us5.datadoghq.com/api/v2/dora/deployment" \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              -H "DD-API-KEY: dcdf193e34d791e91adef59c511ccff6" \
              -d @- << EOF
              {
                "data": {
                  "attributes": {
                    "started_at": "$STARTED_TIME",
                    "finished_at": "$(date +%s),
                    "git": {
                      "commit_sha": "${{ github.sha }}",
                      "repository_url": "${{ github.server_url }}/${{ github.repository }}"
                    },
                    "service": "lab4vini",
                    "version": "1.0",
                  }
                }
              }
              EOF
